### ISSUE TITLE
advanced-browser causes error in anki 23.10 Qt6 after click on "Browse"

### ISSUE THREAD

**Issue by tomitek** [AnKing-VIP/advanced-browser#168]
Diagnostic information
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-5.10.0-14-amd64-x86_64-with-glibc2.38
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-05 21:41:31
Possible involvement of addons: Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 666, in _onBridgeCmd
  File "aqt.toolbar", line 411, in _linkHandler
  File "aqt.toolbar", line 429, in _browseLinkHandler
  File "aqt.main", line 1233, in onBrowse
  File "aqt", line 130, in open
  File "aqt.browser.browser", line 144, in __init__
  File "_aqt.hooks", line 1428, in __call__
  File "/home/tomasz/.var/app/net.ankiweb.Anki/data/Anki2/addons21/874215009/advancedbrowser/core.py", line 43, in _load
    runHook("advBrowserLoaded", self)
  File "anki.hooks", line 34, in runHook
  File "/home/tomasz/.var/app/net.ankiweb.Anki/data/Anki2/addons21/874215009/advancedbrowser/note_fields.py", line 37, in onAdvBrowserLoad
    self.buildMappings()
  File "/home/tomasz/.var/app/net.ankiweb.Anki/data/Anki2/addons21/874215009/advancedbrowser/note_fields.py", line 138, in buildMappings
    self.advBrowser.setupColumns()
  File "/home/tomasz/.var/app/net.ankiweb.Anki/data/Anki2/addons21/874215009/advancedbrowser/core.py", line 95, in setupColumns
    self.table._model.columns[key] = BuiltinColumn(
ValueError: Protocol message Column has no "sorting" field.

**Comment by tomitek** [comment]
Issue solved by reinstalling the add-on.
