### ISSUE TITLE
Error on first time opening after restart

### ISSUE THREAD

**Issue by lloser1** [AnKing-VIP/advanced-browser#170]
Hi, 
when opening Cardbrowser on any deck I get:
![image](https://github.com/AnKing-VIP/advanced-browser/assets/161296317/7facfc37-a007-4a30-97f7-c735e962b78d)

When I press close and reopen browser, everything seems to run normal, until I restart Anki. Any idea, what's wrong?

Debug Code:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 686, in _onBridgeCmd
  File "aqt.toolbar", line 411, in _linkHandler
  File "aqt.toolbar", line 429, in _browseLinkHandler
  File "aqt.main", line 1240, in onBrowse
  File "aqt", line 136, in open
  File "aqt.browser.browser", line 144, in __init__
  File "_aqt.hooks", line 1428, in __call__
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 43, in _load
    runHook("advBrowserLoaded", self)
  File "anki.hooks", line 34, in runHook
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\note_fields.py", line 37, in onAdvBrowserLoad
    self.buildMappings()
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\note_fields.py", line 138, in buildMappings
    self.advBrowser.setupColumns()
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 95, in setupColumns
    self.table._model.columns[key] = BuiltinColumn(
ValueError: Protocol message Column has no "sorting" field.

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T16:34, 'None', '']
Filtered Deck From Tag ['2058067048', 2023-02-19T02:42, 'None', '']
Postpone cards review ['1152543397', 2023-04-15T04:29, 'None', mod]

===IDs of active AnkiWeb add-ons===
1152543397 2058067048 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by lloser1** [comment]
I reinstalled Anki and all Addons, now the problem is gone. Case closed.

**Comment by patarapolw** [comment]
After the Anki update, addon says no need to update; but the fix is to delete the addon and reinstall it. (Only this addon.)

I haven't checked other addons. Do I normally need to delete all addons and reinstall every manually, after the app update?
